Moved all detectors and added test project
microsoft/repo-analysis-detectors pull request #3
Opened 2020-11-27 17:21 UTC by NinadKavimandan

- Moved all detectors,
- Added test console project for local testing
- Renamed assembly to GitHub.RepositoryAnalysis.Detectors

2020-11-27 18:09 UTC, bishal-pdMSFT commented on .gitignore
> +/repo-analysis-detectors.tests.project/bin
the folder name just be `repo-analysis-detectors.tests`.

infact i would suggest folder names as `detectors` and `detectors.tests`

2020-11-27 18:11 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Models/ApplicationSettings.cs
> +    public class ApplicationSettings
you can move the models to be a common project and let that be used by both detectors and tests. Duplicate models can cause drift between test and product code

2020-11-27 18:12 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Models/ApplicationSettings.cs
> +    public class ApplicationSettings
pls add empty line after usings

2020-11-27 18:41 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Program.cs
> +﻿namespace repo_analysis_detectors.tests.project
the namespace looks weird.

2020-11-27 18:42 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Program.cs
> +﻿namespace repo_analysis_detectors.tests.project
I think we should call the folder, namespace and project as TestApp as that what it is. `tests` implies unit/component tests which is not the case here.

2020-11-27 18:43 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Program.cs
> +        async static Task Main(string[] args)
Can you please add a section in readme or a separate doc file to tell how to test changes using this app.

2020-11-27 18:44 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Program.cs
> +                    Id = "NinadKavimandan/hello-worlds", // you can use your own repo for local testing
repo id, branch etc can be made arguments so that user need not change the code to test different sample repos

2020-11-27 18:48 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Program.cs
> +            sourceRepository.Repository.AuthorizationInfo.Parameters.Add("AccessToken", "<USE_YOUR_OWN_PAT>");
This would force user to code their PAT which is a security issue.

We can use an environment variable and ask user to set that variable before running app. If they do not set then as PAT at runtime as a console input (password type)

2020-11-27 18:59 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/Program.cs
> +            return deployTargetSettingsList;
This is lot of code in test app. This essentially means that the product exposes APIs in such a way that there are many functions and consumer (test app in this case, and PE repo analysis service in real) would have to do all this to consume the detectors. This has two problem:
1. Difficult to understand and consume.
2. detectors and consumers are tightly coupled and hence any change in either has good chance of causing compat issue.

I had put a comment in PE side PR to move a bunch of logic to language detector  from RepoAnalysis service class. I feel doing so would break this hard coupling and make things better here in test app as well.

2020-11-27 19:08 UTC, bishal-pdMSFT commented on repo-analysis-detectors.tests.project/TreeAnalysisService.cs
> +        private async Task ConvertGitTreeToTreeAnalysis(IList<FileSystemTreeNode> repositoryTree,SourceRepository sourceRepository, TreeAnalysis treeAnalysis)
This class has two types of functionalities:
1. function ConvertGitTreeToTreeAnalysis which just processes tree data. This can be move to a separate GitTree helper project and re-used in PE repo analysis as well. This will reduce duplicate code across two repos. And will also ensure that there is least diff between product code and test app
2. Rest of the functions are making API calls - getting tree, getting file content etc. They can be kept here inside test app for now. And PE can use its own vssf based code. later we can think of using this piece in PE as well if we can be confident that this code is as good/resilient and performant as vssf code.

2020-11-27 19:09 UTC, bishal-pdMSFT commented on repo-analysis-detectors/BuildTargetDetectors/PythonDjangoBuildTargetDetector.cs
> +﻿namespace GitHub.RepositoryAnalysis.Detectors.BuildTargetDetectors
I am not really going through code of each detector and assume that there is no noticeable difference between these and PE service ones.

2020-11-27 19:09 UTC, bishal-pdMSFT requested changes
Left some comments. Please check.

2020-11-28 04:51 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +            return deployTargetSettingsList;
Agreed. Intent behind getting `BuildTargetSettings`, `DeployTargetSettings` and `ApplicationSettings` in RepoAnalysisService was to not expose the logic for this repo. I think optimal way to consume would be to shift ApplicationSettings logic to `LanguageDetectorBase` as well, as it was earlier.

2020-11-28 04:56 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/TreeAnalysisService.cs
> +        private async Task ConvertGitTreeToTreeAnalysis(IList<FileSystemTreeNode> repositoryTree,SourceRepository sourceRepository, TreeAnalysis treeAnalysis)
To the first point, this is exactly similar to what we have in PE already. May be this can be consumed as well in PE side as we are doing for detectors.
To the second point, this is just plain a `HttpClient`, will have to compare the performance a bit with the `GitHubHttpClient` we are using in vssf, although it is also using `HttpClient` only internally.

2020-11-28 04:57 UTC, NinadKavimandan commented on repo-analysis-detectors/BuildTargetDetectors/PythonDjangoBuildTargetDetector.cs
> +﻿namespace GitHub.RepositoryAnalysis.Detectors.BuildTargetDetectors
It's just a namespace change

2020-11-28 05:03 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Models/ApplicationSettings.cs
> +    public class ApplicationSettings
None of the models from test are being used in detectors, as these are typically the response json classes after HTTP calls from the testApp. Instead we can use the client contract nuget from PE side, as some of the models exposed in that library are being used in the test app.

2020-11-28 05:03 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +﻿namespace repo_analysis_detectors.tests.project
yeah i felt the same. will do that

2020-11-28 05:03 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +                    Id = "NinadKavimandan/hello-worlds", // you can use your own repo for local testing
okay it makes sense. will do that

2020-11-29 04:32 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +        async static Task Main(string[] args)
added to readme

2020-11-29 04:32 UTC, NinadKavimandan commented on .gitignore
> +/repo-analysis-detectors.tests.project/bin
done

2020-11-29 04:33 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Models/ApplicationSettings.cs
> +    public class ApplicationSettings
using the contract nuget from PE now. only issue being `SourceRepository` has `private set` property on Parameters instead `AuthorizationInfo`, this is making the deserialization ignore the AccessToken, thus using a custom class for now, will update the PE side nuget a bit to get it to work with the testApp

2020-11-29 04:34 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +            sourceRepository.Repository.AuthorizationInfo.Parameters.Add("AccessToken", "<USE_YOUR_OWN_PAT>");
converted the console app to web app

2020-11-29 04:34 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +            sourceRepository.Repository.AuthorizationInfo.Parameters.Add("AccessToken", "<USE_YOUR_OWN_PAT>");
this will work the same way as our repository analysis, nothing needs to be set in the code explicitly

2020-11-29 04:34 UTC, NinadKavimandan commented on repo-analysis-detectors.tests.project/Program.cs
> +            sourceRepository.Repository.AuthorizationInfo.Parameters.Add("AccessToken", "<USE_YOUR_OWN_PAT>");
this felt like the safest option to go with

2020-12-03 04:03 UTC, NinadKavimandan commented on Detectors/Models/RepositoryAnalysis.cs
> +    public class RepositoryAnalysis
As per the discussion, we were to duplicate `ApplicationSettings`, but `RepositoryAnalysis` from contract was using that as well, thus to avoid tampering with the contract class, I decided to duplicate `RepositoryAnalysis` as well. @bishal-pdMSFT

2020-12-03 10:01 UTC, bishal-pdMSFT commented on Detectors/BuildTargetDetectors/DockerfileBuildTargetDetector.cs
> +    public class DockerfileBuildTargetDetector : BuildTargetDetectorBase
I am assuming there is no difference in the business logic of these detectors and hence not reviewing in details.
Please call out the diffs if that is not the case.

2020-12-03 10:08 UTC, NinadKavimandan commented on Detectors/BuildTargetDetectors/DockerfileBuildTargetDetector.cs
> +    public class DockerfileBuildTargetDetector : BuildTargetDetectorBase
no difference

2020-12-03 10:16 UTC, bishal-pdMSFT commented on Detectors/LanguageDetectors/LanguageDetectorBase.cs
> +        public IList<BuildTargetSettings> GetBuildTargetSettingsList(TreeAnalysis treeAnalysis)
If I am not wrong, this function was moved earlier to RepoAnalysis service in PE. But now that all detectors are in this repo itself, this function has been moved to language detector where it makes more sense.
Is this understanding correct?

2020-12-03 10:29 UTC, bishal-pdMSFT commented on Detectors/Models/ApplicationSettings.cs
> +    public class ApplicationSettings
1. I hope some of the models which are moved here will no longer be needed in PE code and can be removed from there.
2. Some, which are needed by PE's client contract and are needed here as well, will obviously be a duplicate. But from PE code's perspective, we should not treat them as implicit duplicate and treat them as two different entities. This mean we will write a converter layer in PE which will convert from model defined here to the one defined in PE. The converter will be very simple one today and will just clone the properties, but can be useful in future if case these two drift apart.

2020-12-03 10:31 UTC, bishal-pdMSFT commented on Detectors/Models/RepositoryAnalysis.cs
> +    public class RepositoryAnalysis
Is `RepositoryAnalysis` used in this repo? If no, then I would advise against that. Please look at my above comment.

2020-12-03 10:34 UTC, bishal-pdMSFT commented on TestApp/RepositoryAnalysisService.cs
> +        private RepositoryAnalysis StartE2EFlow(TreeAnalysis treeAnalysis)
This does not qualify as a usage of `RepositoryAnalysis` as it is a test app. If this is the only project, then move `RepositoryAnalysis` to inside test app folder.

2020-12-03 10:38 UTC, bishal-pdMSFT approved these changes

2020-12-03 10:41 UTC, NinadKavimandan commented on Detectors/LanguageDetectors/LanguageDetectorBase.cs
> +        public IList<BuildTargetSettings> GetBuildTargetSettingsList(TreeAnalysis treeAnalysis)
yes!

2020-12-03 10:45 UTC, NinadKavimandan commented on Detectors/Models/ApplicationSettings.cs
> +    public class ApplicationSettings
1) -> yes we can remove some from PE side.
2) -> converter layer sounds like a good idea, that will remove the necessity of having to use `RepositoryAnalysis` object here, as we can convert `ApplicationSettings` from this repo to the one in PE.

2020-12-03 10:46 UTC, NinadKavimandan commented on TestApp/RepositoryAnalysisService.cs
> +        private RepositoryAnalysis StartE2EFlow(TreeAnalysis treeAnalysis)
Moved `RepositoryAnalysis` here as it was using `ApplicationSettings`, and is a part of the contract itself. Although having the converter layer will solve this problem, so will do that instead!

2020-12-03 12:15 UTC, NinadKavimandan commented on Detectors/Models/RepositoryAnalysis.cs
> +    public class RepositoryAnalysis
moved it to Test

2020-12-03 12:23 UTC, NinadKavimandan commented
Merging!

2020-12-03 12:23 UTC, merged